version: '3'

services:
  nginx:
    container_name: dev-nginx
    image: nginx
    ports:
      - '8080:80'
    links:
      - phpfpm
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/access.log:/var/log/nginx/access.log
      - ./docker/logs/error.log:/var/log/nginx/error.log

  phpfpm:
    container_name: dev-php
    build:
      context: .
      dockerfile: ./docker/phpfpm.docker
    image: dev/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www